#!/bin/bash

# Session
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway
export XDG_CONFIG_HOME="$HOME/.config"
export QT_QPA_PLATFORM="wayland;xcb"
export WLR_NO_HARDWARE_CURSORS=1

# Wayland stuff
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1

# BEMOJI
export BEMOJI_PICKER_CMD="wofi --dmenu"

mkdir -p /tmp/sway
sway &> "/tmp/sway/$(date +"%Y_%m_%d_%I_%M_%p").log"

