# dynamic_padding = true
import = [
	"~/.config/alacritty/themes/catppuccin/catppuccin-frappe.toml",
	# uncomment the flavour you want below:
	# "~/.config/alacritty/themes/catppuccin/catppuccin-mocha.toml",
	# "~/.config/alacritty/themes/catppuccin/catppuccin-macchiato.toml",
	# "~/.config/alacritty/themes/catppuccin/catppuccin-latte.toml",
]
live_config_reload = true

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[window]
opacity = 0.899

[window.padding]
x = 5
y = 5
