#!/bin/sh

cd ~

export XDG_CURRENT_DESKTOP=sway
# Session
export XDG_SESSION_TYPE=wayland
export XDG_CONFIG_HOME="$HOME/.config"
export QT_QPA_PLATFORM="wayland;xcb"
export WLR_NO_HARDWARE_CURSORS=1

# Wayland stuff
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1

# Log WLR errors and logs to the hyprland log. Recommended
export HYPRLAND_LOG_WLR=1

# Tell XWayland to use a cursor theme
export XCURSOR_THEME=Bibata-Modern-Classic

# Set a cursor size
export XCURSOR_SIZE=24

# Example IME Support: fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export SDL_IM_MODULE=fcitx
export GLFW_IM_MODULE=ibus

dbus-launch --sh-syntax --exit-with-session Hyprland

