#!/bin/sh

down() {
	brightnessctl s 2%- -q
	brightness=$(brightnessctl -m | cut -d',' -f4)
	dunstify -a "BRIGHTNESS" "Decreasing to $brightness%" -h int:value:"$brightness" -i ~/.config/dunst/assets/ui/brightness-low.svg -r 2593 -u normal
}

up() {
	brightnessctl s +2% -q
	brightness=$(brightnessctl -m | cut -d',' -f4)
	dunstify -a "BRIGHTNESS" "Increasing to $brightness%" -h int:value:"$brightness" -i ~/.config/dunst/assets/ui/brightness-high.svg -r 2593 -u normal
}

case "$1" in
up) up ;;
down) down ;;
esac
